apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wqge6y83k-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wqge6y83k-nodejs 
  name: wqge6y83k-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wqge6y83k-nodejs 
