apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wqge6y83k-nodejs-gitops
  description: This is GitOps manifest for wqge6y83k-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=wqge6y83k-nodejs
    backstage.io/kubernetes-id: wqge6y83k-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: wqge6y83k-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wqge6y83k-nodejs
